const npcBlockedRemarks = [
  'Excuse me.',
  'Move please.',
  'Out of the way, if you do not mind.',
  'Sorry, I need to get through.',
  'Could you let me pass?',
  'I am trying to catch the train.',
  'Pardon me, coming through.',
  'You are standing right where I need to be.',
  'Mind your step, please.',
  'Make way, please.',
];

export const npcDefinitions = [
  {
    key: 'stationMaster',
    name: 'Constance Bell',
    age: 58,
    gender: 'woman',
    role: 'station master',
    goal: 'unlock the side-room door at minute thirty, lock it at minute seventy-five, and keep passengers off the tracks',
    gunfireReaction: 'drops her brass whistle, orders everyone behind cover, then tries to preserve the timetable from a safe doorway',
    description: 'Constance Bell, 58, is the station master; she keeps one eye on the train, one hand on a heavy brass key, and a private ledger of every impossible loop.',
    dialogue: [
      'Constance Bell says, “Rules are rules. That side room opens at half past and closes at minute seventy-five.”',
      'Constance Bell pats a brass key. “If you hear me lock it, do not linger below.”',
      'Constance Bell says, “My goal is simple: keep this platform orderly until the clock admits what it has done.”',
      'Constance Bell says, “Off the tracks at once! Timetables are difficult enough without trespassers.”',
    ],
    blockedRemarks: [
      'Constance Bell says, “Stand clear, please. I have a door to attend.”',
      'Constance Bell rattles the keyring. “Official business.”',
    ],
    routePreference: 'station master timed door',
  },

  {
    key: 'police-0',
    name: 'Sergeant Ada Rook',
    age: 41,
    gender: 'woman',
    role: 'police officer',
    goal: 'patrol the station concourse, deter violence, and arrest anyone who fires a weapon',
    gunfireReaction: 'draws her baton, blows a whistle, and chases the shooter until she can make an arrest',
    description: 'Sergeant Ada Rook, 41, is a police officer posted at the station; she watches for trouble and remembers more of each loop than she admits.',
    dialogue: [
      'Sergeant Ada Rook says, “Keep moving and stay out of trouble. I have arrested the same pickpocket six times today.”',
      'Sergeant Ada Rook says, “My goal is to keep this station safe until headquarters believes the clocks are broken.”',
      'Sergeant Ada Rook says, “If I hear a gunshot, I chase the shooter. No exceptions, not even temporal ones.”',
    ],
    blockedRemarks: [
      'Sergeant Ada Rook says, “Step aside.”',
      'Sergeant Ada Rook says, “Official business.”',
    ],
    routePreference: 'police station patrol',
  },
  {
    key: 'police-1',
    name: 'PC Jonah Flint',
    age: 24,
    gender: 'man',
    role: 'police officer',
    goal: 'guard the station clock, note every suspicious reset, and back up Sergeant Rook when violence breaks out',
    gunfireReaction: 'fumbles for his whistle, then sprints after the shooter with more courage than grace',
    description: 'PC Jonah Flint, 24, is a rookie police officer assigned to the station clock with a fresh notebook and badly hidden nerves.',
    dialogue: [
      'PC Jonah Flint says, “Sergeant Rook told me to watch the clock. It blinked first.”',
      'PC Jonah Flint says, “My goal is to write one report that does not get reset at noon.”',
      'PC Jonah Flint says, “If someone fires a gun, I chase them. That was in training, though training did not mention time travel.”',
    ],
    blockedRemarks: [
      'PC Jonah Flint says, “Please step aside. I am trying to look official.”',
      'PC Jonah Flint says, “Official business, probably.”',
    ],
    routePreference: 'police station patrol',
  },
  {
    key: 'policeGuard',
    name: 'Constable Bram Ives',
    age: 29,
    gender: 'man',
    role: 'police guard',
    goal: 'guard the holding cell until the loop resets and prevent prisoners from wandering back into the station',
    gunfireReaction: 'locks down the cells, shouts for Sergeant Rook, and blocks the nearest exit',
    description: 'Constable Bram Ives, 29, stands watch over the station cells with tired eyes and a notebook full of reset times.',
    dialogue: [
      'Constable Bram Ives says, “You will wait here until this strange day resets.”',
      'Constable Bram Ives says, “My goal is to keep the cell closed, even if the clock keeps reopening the day.”',
      'Constable Bram Ives says, “No visitors. No release. Not before the clock turns over.”',
    ],
    blockedRemarks: [
      'Constable Bram Ives says, “Back in the cell.”',
    ],
    routePreference: 'police station guard',
  },
  {
    key: 'homelessPerson',
    name: 'Robin Vale',
    age: 49,
    gender: 'man',
    role: 'homeless person',
    goal: 'sit near the shop doorway, collect enough change for a hot drink, and avoid being moved on before the loop resets',
    gunfireReaction: 'scrambles away from the shopfront and runs for the safest corner he can find',
    description: 'Robin Vale, 49, is a homeless person sitting near the shop with a patched blanket, a paper cup, and wary eyes trained on the repeating crowd.',
    dialogue: [
      'Robin Vale says, “Spare a coin for tea? The morning keeps coming back, but hunger does not reset kindly.”',
      'Robin Vale lifts a paper cup. “If you can spare money, I can make this loop a little warmer.”',
      'Robin Vale says, “My goal is just enough change for something hot before the station forgets me again.”',
    ],
    blockedRemarks: [
      'Robin Vale gathers his blanket closer. “Mind the cup, please.”',
      'Robin Vale says, “Easy there. I am sitting here.”',
    ],
    routePreference: 'homeless seated by shop',
  },
  {
    key: 'commuter',
    name: 'Mara Vale',
    age: 34,
    gender: 'woman',
    role: 'commuter',
    goal: 'board the next train and reach a tribunal hearing before the loop steals her testimony again',
    gunfireReaction: 'clutches her briefcase to her chest and runs for the farthest platform exit',
    description: 'Mara Vale, 34, is a raincoated commuter carrying sealed testimony and checking the platform clock every few breaths.',
    dialogue: [
      'Mara Vale says, “If I miss this train again, I am blaming the clock.”',
      'Mara Vale says, “The same two hours, the same platform, the same late hearing.”',
      'Mara Vale says, “Please let me through. My goal is to board before the doors learn my name again.”',
    ],
    blockedRemarks: [
      'Mara Vale says, “Sorry, that train is mine.”',
      'Mara Vale taps her ticket. “Platform, please.”',
    ],
    routePreference: 'commuter to train',
  },
  {
    key: 'shopkeeper',
    name: 'Oren Pike',
    age: 63,
    gender: 'man',
    role: 'shopkeeper',
    goal: 'reopen the kiosk, balance the till, and find the missing delivery invoice',
    gunfireReaction: 'dives behind a newspaper rack and yells that the kiosk is closed indefinitely',
    description: 'Oren Pike, 63, is a shopkeeper with ink-stained fingers, a coin apron, and a suspicion that his till is counting backward.',
    dialogue: [
      'Oren Pike says, “The kiosk clock loses a minute whenever nobody watches it.”',
      'Oren Pike says, “I keep restocking yesterday’s papers.”',
      'Oren Pike says, “My goal is to get back to the counter before the delivery invoice vanishes again.”',
    ],
    blockedRemarks: [
      'Oren Pike says, “Mind the papers, please.”',
      'Oren Pike says, “I need to get back to the counter.”',
    ],
    routePreference: 'shopkeeper to kiosk',
  },
  {
    key: 'tourist',
    name: 'Elsie Rowan',
    age: 72,
    gender: 'woman',
    role: 'tourist',
    goal: 'find the museum exit and prove her upside-down timetable is not upside-down in the next loop',
    gunfireReaction: 'folds herself behind the nearest bench and recites emergency phrases from her phrasebook',
    description: 'Elsie Rowan, 72, is a lost tourist circling the platform with an upside-down timetable and three contradictory postcards.',
    dialogue: [
      'Elsie Rowan says, “Does this platform go to tomorrow, or only back to noon?”',
      'Elsie Rowan says, “I have asked for directions three times. The answers keep changing.”',
      'Elsie Rowan says, “My goal is the museum exit, unless that bench is the museum.”',
    ],
    blockedRemarks: [
      'Elsie Rowan says, “Oh! Is this the way to the platform?”',
      'Elsie Rowan studies her map. “I thought I had just passed here.”',
    ],
    routePreference: 'lost tourist pacing near platform',
  },
  {
    key: 'courier',
    name: 'Noor Patel',
    age: 26,
    gender: 'nonbinary',
    role: 'bicycle courier',
    goal: 'deliver a tube of blueprints to floor four of the office block before the recipient forgets ordering it',
    gunfireReaction: 'sprints for the office stairwell, keeping the blueprint tube between them and the shot',
    description: 'Noor Patel, 26, is a nonbinary courier with a dented helmet and a blueprint tube labeled FLOOR FOUR ONLY.',
    dialogue: [
      'Noor Patel says, “Fourth floor, blueprints, signature in blue ink. That is the goal.”',
      'Noor Patel says, “The elevator never arrives, so I race the stairs every loop.”',
      'Noor Patel taps the tube. “If this plan is for a time machine, I want overtime.”',
    ],
    routePreference: 'office delivery',
  },
  {
    key: 'accountant',
    name: 'Victor Saye',
    age: 47,
    gender: 'man',
    role: 'accountant',
    goal: 'wait by the reception desk until the minute hand repeats, then compare two impossible ledgers',
    gunfireReaction: 'crawls under the reception desk and starts counting seconds between echoes',
    description: 'Victor Saye, 47, is an accountant with silver spectacles, two ledgers, and a pencil sharpened down to a stub.',
    dialogue: [
      'Victor Saye says, “Debit: one missing afternoon. Credit: one dreadful headache.”',
      'Victor Saye says, “My goal is to prove the books balance even when time does not.”',
      'Victor Saye says, “Please do not step on the receipts. They are evidence.”',
    ],
    routePreference: 'office reception waiting',
  },
  {
    key: 'janitor',
    name: 'Greta Moss',
    age: 55,
    gender: 'woman',
    role: 'janitor',
    goal: 'mop the same coffee spill on floor one and find out who keeps making it before it happens',
    gunfireReaction: 'runs toward the utility closet, dragging her mop like a barricade',
    description: 'Greta Moss, 55, is a janitor with a yellow bucket, a master key, and a feud with a coffee stain that keeps reappearing.',
    dialogue: [
      'Greta Moss says, “I mop it, the clock hiccups, and the coffee is back.”',
      'Greta Moss says, “My goal is to catch the spiller before the spill exists.”',
      'Greta Moss says, “Careful. Wet floor, dry timeline, no guarantees.”',
    ],
    routePreference: 'office wandering',
  },
  {
    key: 'engineer',
    name: 'Dr. Lina Ko',
    age: 39,
    gender: 'woman',
    role: 'systems engineer',
    goal: 'reach the server desk on floor two and stop a prototype clock from syncing with the station',
    gunfireReaction: 'ducks behind a desk and protects a notebook covered in circuit diagrams',
    description: 'Dr. Lina Ko, 39, is a systems engineer in a grease-smudged blazer, carrying a notebook of clockwork circuit diagrams.',
    dialogue: [
      'Dr. Lina Ko says, “If the station clock and office server agree, the loop tightens.”',
      'Dr. Lina Ko says, “My goal is floor two. There is a prototype there pretending to be a clock.”',
      'Dr. Lina Ko says, “Do not trust anything that ticks in binary.”',
    ],
    routePreference: 'office wandering',
  },
  {
    key: 'intern',
    name: 'Pip Haldane',
    age: 19,
    gender: 'man',
    role: 'office intern',
    goal: 'carry tea to floor three without forgetting who asked for sugar',
    gunfireReaction: 'drops the tea tray, apologizes to everyone, and bolts for the stairs',
    description: 'Pip Haldane, 19, is an office intern balancing a tea tray, sticky notes, and visible panic about his first day repeating forever.',
    dialogue: [
      'Pip Haldane says, “Two sugars? No sugars? I wrote it down, then the note reset.”',
      'Pip Haldane says, “My goal is floor three with all mugs intact.”',
      'Pip Haldane says, “If today is my first day forever, do I ever get promoted?”',
    ],
    routePreference: 'office wandering',
  },
  {
    key: 'solicitor',
    name: 'Amara Finch',
    age: 44,
    gender: 'woman',
    role: 'solicitor',
    goal: 'wait outside the third-floor boardroom until her missing client arrives from a previous loop',
    gunfireReaction: 'retreats behind the heaviest door and announces she is a witness',
    description: 'Amara Finch, 44, is a solicitor in a charcoal suit, holding a stamped injunction against “unauthorized chronology.”',
    dialogue: [
      'Amara Finch says, “My client entered this building yesterday and may arrive today from last week.”',
      'Amara Finch says, “My goal is to serve these papers before causality objects.”',
      'Amara Finch says, “For the record, this conversation may have already happened.”',
    ],
    routePreference: 'office wandering',
  },
  {
    key: 'inventor',
    name: 'Edwin Quill',
    age: 68,
    gender: 'man',
    role: 'retired inventor',
    goal: 'wait on floor four for the roof signal and test whether pigeons ignore time loops',
    gunfireReaction: 'flattens against the wall and shields a cage of very offended pigeons',
    description: 'Edwin Quill, 68, is a retired inventor with brass goggles, a pigeon cage, and a receiver tuned to the station clock.',
    dialogue: [
      'Edwin Quill says, “My goal is the roof signal. The pigeons know when it is about to happen.”',
      'Edwin Quill says, “Never build a clock you cannot apologize to.”',
      'Edwin Quill says, “If a pigeon arrives before it leaves, write that down.”',
    ],
    routePreference: 'office wandering',
  },
  {
    key: 'conductor',
    name: 'Silas Penn',
    age: 52,
    gender: 'man',
    role: 'train conductor',
    goal: 'wait beside the platform and decide whether to board the train he insists he already drove',
    gunfireReaction: 'blows his conductor whistle and runs toward the guard room',
    description: 'Silas Penn, 52, is an off-duty train conductor with a punched cap, a silver whistle, and a memory of arriving before departure.',
    dialogue: [
      'Silas Penn says, “I drove that train in, then stepped off and found myself waiting for it.”',
      'Silas Penn says, “My goal is to learn whether boarding fixes me or doubles me.”',
      'Silas Penn says, “A whistle means depart, except when it means hide.”',
    ],
    routePreference: 'commuter to train',
  },
  {
    key: 'violinist',
    name: 'Talia Reed',
    age: 31,
    gender: 'woman',
    role: 'street violinist',
    goal: 'wait beneath the lamp and finish a song that changes key every reset',
    gunfireReaction: 'snaps her violin case shut and runs behind the ticket barriers',
    description: 'Talia Reed, 31, is a street violinist with rosin on her sleeves and sheet music annotated by future versions of herself.',
    dialogue: [
      'Talia Reed says, “The last bar changes every loop. My goal is to catch it before it catches me.”',
      'Talia Reed says, “If you hear the melody backward, leave the platform.”',
      'Talia Reed says, “Coins reset. Applause does not.”',
    ],
    routePreference: 'lost tourist pacing near platform',
  },
  {
    key: 'porter',
    name: 'Hugo Marsh',
    age: 36,
    gender: 'man',
    role: 'porter',
    goal: 'carry an unclaimed suitcase to lost property and avoid opening it before it starts ticking',
    gunfireReaction: 'abandons the suitcase for exactly one second, then drags it behind a pillar',
    description: 'Hugo Marsh, 36, is a porter with a red scarf and an unclaimed suitcase that sometimes hums in perfect time with the clock.',
    dialogue: [
      'Hugo Marsh says, “My goal is lost property. The suitcase prefers found trouble.”',
      'Hugo Marsh says, “If it starts ticking, please pretend you did not hear it.”',
      'Hugo Marsh says, “Heavy bags, light schedule, impossible day.”',
    ],
    routePreference: 'shopkeeper to kiosk',
  },
];

export const npcMapSymbols = {
  N: { defaultProfile: true },
  H: { profileKey: 'homelessPerson', uniquePerMap: true },
  M: { profileKey: 'stationMaster', uniquePerMap: true },
  Z: { profileKey: 'police' },
  J: { profileKey: 'policeGuard' },
};

export { npcBlockedRemarks };
