export const terrain = {
  '#': { color: 0x38404d, blocks: true, description: 'A solid wall blocks the way.' },
  '.': { color: 0x656b72, blocks: false, blocksView: false, description: 'Station paving.' },
  'h': { color: 0x1f2933, blocks: false, blocksView: false, road: true, description: 'A busy two-lane road. Traffic keeps left, and the cars do not stop for time travelers.' },
  '-': { color: 0x7f858c, blocks: false, blocksView: false, description: 'A raised platform edge running beside the track.' },
  '=': { color: 0x20242a, blocks: false, blocksView: false, track: true, description: 'The train tracks hum with dangerous loop-energy. The station master will not approve.' },
  'T': { color: 0x335f8f, blocks: false, blocksView: true, train: true, description: 'The waiting train. Step back aboard to end this loop.' },
  'D': { color: 0x9b6a3c, blocks: false, blocksView: true, description: 'An open doorway blocks your line of sight, but you can pass through.' },
  'W': { color: 0x4f6f8c, blocks: true, blocksView: false, description: 'A glass window blocks the way, but you can see through it.' },
  '~': { color: 0x317345, blocks: false, description: 'A patch of grass.' },
  'B': { color: 0x80613a, blocks: false, interact: 'You sit for a minute and watch the station repeat itself.', description: 'A station bench.' },
  'C': { color: 0x8d99ae, blocks: true, blocksView: false, description: 'A parked car.' },
  'S': { color: 0xa855f7, blocks: true, blocksView: false, interact: 'The shop window is full of headlines you swear you have already read.', description: 'A small shop.' },
  'K': { color: 0xf6c453, blocks: true, blocksView: false, interact: 'The kiosk clock ticks forward exactly one minute.', description: 'A kiosk.' },
  'A': { color: 0x2dd4bf, blocks: true, blocksView: false, interact: 'The board flips through destinations you remember from previous loops.', description: 'An announcement board listing departures and impossible delays.' },
  'L': { color: 0xfff3a3, blocks: true, blocksView: false, interact: 'The lamp hums warmly, then flickers in a rhythm you almost recognize.', description: 'A platform lamp casting a steady pool of light.' },
  'V': { color: 0xef4444, blocks: true, blocksView: false, interact: 'The vending machine offers the same snack from three different hours.', description: 'A humming vending machine.' },
  'G': { color: 0x9b6a3c, blocks: true, blocksView: false, interact: 'The luggage tag is addressed to a date that has not happened yet.', description: 'A stack of unattended luggage.' },
  'R': { color: 0x64748b, blocks: true, blocksView: false, interact: 'The ticket barrier rejects your ticket, then stamps tomorrow on it.', description: 'A closed ticket barrier.' },
  'O': { color: 0xf8fafc, blocks: true, blocksView: false, interact: 'The station clock ticks once, but every hand points toward departure.', description: 'A round station clock.' },
  'N': { color: 0xff8a65, blocks: true, blocksView: false, npc: true, interact: 'They mutter about catching the same train again.', description: 'A townsperson.' },
  'M': { color: 0x38bdf8, blocks: true, blocksView: false, npc: true, interact: 'The station master checks a brass key and the platform clock.', description: 'The station master.' },
  'X': { color: 0x5b3418, blocks: true, blocksView: true, lockedDoor: true, interact: 'The station side-room door is locked tight.', description: 'A locked station side-room door.' },
  'U': { color: 0xa78bfa, blocks: false, blocksView: false, stairs: true, description: 'A narrow stairwell descends beneath the station.' },
  '^': { color: 0x22c55e, blocks: false, blocksView: false, stairsUp: true, description: 'Stairs marked with an upward arrow.' },
  'v': { color: 0xf97316, blocks: false, blocksView: false, stairsDown: true, description: 'Stairs marked with a downward arrow.' },
  'E': { color: 0x475569, blocks: false, blocksView: true, officeEntrance: true, description: 'The glass entrance to an office block.' },
  'Q': { color: 0x475569, blocks: false, blocksView: true, officeExit: true, description: 'The office block exit back to the station district.' },
  'r': { color: 0x8b5cf6, blocks: true, blocksView: false, interact: 'The reception desk has a visitor book filled with today repeated line after line.', description: 'A reception desk for the office block.' },
  'o': { color: 0x94a3b8, blocks: true, blocksView: false, interact: 'The desk is covered in coffee rings, memos, and a calendar stuck on this date.', description: 'An office desk.' },
  'p': { color: 0x16a34a, blocks: true, blocksView: false, interact: 'The plant seems healthier each time the loop starts over.', description: 'A potted office plant.' },
  'P': { color: 0x656b72, blocks: false, start: true, description: 'Your starting point on the platform.' },
  ' ': { color: 0x111111, blocks: true, description: 'An unmapped void.' },
};
